### ISSUE TITLE
error: VNDK library: libbinder's ABI has EXTENDING CHANGES

### ISSUE THREAD

**Issue by gabrielfsousa** [Evolution-X-AOSP/frameworks_native#4]
FAILED: /ANDROID/evoX/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm_armv8-a_shared/libbinder.so.abidiff
(prebuilts/clang-tools/linux-x86/bin/header-abi-diff -allow-unreferenced-changes -allow-unreferenced-elf-symbol-changes -lib libbinder -arch arm -o /ANDROID/evoX/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm_armv8-a_shared/libbinder.so.abidiff -new /ANDROID/evoX/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm_armv8-a_shared/libbinder.so.lsdump -old prebuilts/abi-dumps/vndk/30/64/arm_armv8-a/source-based/libbinder.so.lsdump)|| (echo 'error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py  -l libbinder' && (mkdir -p $DIST_DIR/abidiffs && cp /ANDROID/evoX/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm_armv8-a_shared/libbinder.so.abidiff $DIST_DIR/abidiffs/) && exit 1)
******************************************************
error: VNDK library: libbinder's ABI has EXTENDING CHANGES Please check compatibility report at: /ANDROID/evoX/out/soong/.intermediates/frameworks/native/libs/binder/libbinder/android_vendor.30_arm_armv8-a_shared/libbinder.so.abidiff
******************************************************
error: Please update ABI references with: $ANDROID_BUILD_TOP/development/vndk/tools/header-checker/utils/create_reference_dumps.py  -l libbinder

**Comment by Guri85** [comment]
same any help???
